### ISSUE TITLE
python 3.10, ubuntu 18.04 cannot pass test

### ISSUE THREAD

**Issue by klae01** [oittaa/uuid6-python#38]
I saw that `OS Independent` written in setup.py, and I was working on adding an OS other than ubuntu to the action.

But `uuid_7` cannot pass a single testing; function `test_time` of class `UUIDTests` in `test/test_uuid6.py`

Is it critically big difference? or is it safe enough? 

```
....F............
======================================================================
FAIL: test_time (test.test_uuid6.UUIDTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/me/work/uuid6-python/uuid6-python/test/test_uuid6.py", line 102, in test_time
    self.assertAlmostEqual(uuid_6.time / 10**7, uuid_1.time / 10**7, 3)
AssertionError: 13869195802.594696 != 13869195802.591389 within 3 places (0.003307342529296875 difference)

----------------------------------------------------------------------
Ran 17 tests in 0.592s

FAILED (failures=1)
```

**Comment by oittaa** [comment]
If this was in virtual machine, I would guess either it was a slow configuration and didn't execute the commands within 0.001 seconds or the clock wasn't accurate enough.
