### ISSUE TITLE
JS implementation for UUIDv7

### ISSUE THREAD

**Issue by jcary741** [oittaa/uuid6-python#60]
I had a frontend that I wanted to sometimes generate an ID, and since I'm already playing with using UUIDv7 in my (Python) backend, I thought I'd just figure out how to use that in JS as well.

Anyway, I don't know where it should live, but since it's almost a direct translation of the code in this repo, I thought I'd just post it back here in case someone else finds it useful: https://gist.github.com/jcary741/8b27e5bb821e65457c06e5b6160837dd

@oittaa Thank you so much for creating this great python library! I'm so excited about the new UUID versions, but wouldn't have been able to even try them out without your work to implement them in Python.

**Comment by oittaa** [comment]
Cool, there's also an official list of different implementations, if you'd like to submit yours. https://github.com/uuid6/prototypes
