### ISSUE TITLE
Max UUID

### ISSUE THREAD

**Issue by 0xflotus** [oittaa/uuid6-python#75]
[The draft](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format#section-5.4) specifies a max UUID of FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF. Do you think you need this special UUID as a feature in this library?

<img width="608" alt="Bildschirmfoto 2022-11-15 um 23 36 30" src="https://user-images.githubusercontent.com/26602940/202039558-1c5595f3-922a-4212-9c25-032ec2749d7b.png">

**Comment by jleclanche** [comment]
If you ever need the max UUID you can always use this:

```py
from uuid import UUID
>>> UUID(int=2**128 - 1)
UUID('ffffffff-ffff-ffff-ffff-ffffffffffff')
```

There's no difference with doing it from uuid6 as the lib generates UUID objects.

**Comment by oittaa** [comment]
There's also the "Nil UUID" in the spec. I just don't know if there's much value to define "Nil UUID" and "Max UUID" in this library. You can do it like @jleclanche showed above or like they do in [the official library](https://github.com/python/cpython/blob/3.11/Lib/uuid.py#L733-L736).

```
from uuid import UUID
UUID_NIL = UUID('00000000-0000-0000-0000-000000000000')
UUID_MAX = UUID('ffffffff-ffff-ffff-ffff-ffffffffffff')
```
